### ISSUE TITLE
your code nuked 3 of my servers thru the bot.

### ISSUE THREAD

**Issue by tgrafk12** [SudhanPlayz/Discord-MusicBot#1170]
**Please describe the problem you are having in as much detail as possible:**

### Essentials:

- Bot Version:
- Commit Hash:
- Node.js version:
- Operating system:

#### Additional system info
- Is it virtualized? (Docker or ...) :
- What CPU is it running on (X86 or ARM or...):
- Additional details that might help us figure out the problem:

### Relevant client options:

- partials: none
- gateway intents: none
- other: none

**Comment by tgrafk12** [comment]
remove your code at once, im reporting this repo.

**Comment by Assassin654** [comment]
> remove your code at once, im reporting this repo.

Where did you host your bot

**Comment by sprucecellodev125** [comment]
Thanks for explaining @daichuanwu21.

We recommend to stop using replit/glitch and switch to another hosting provider. If you can't find one, I recommend stozu.net or discloud. Feel free to @ me or another maintainer if you have another question.

**Comment by LewdHuTao** [comment]
Bet youre hosting your bot in replit. Also there is no reason to report this repo as it is your own fault. Get better hosting so that people can easily scrap your token

**Comment by LewdHuTao** [comment]
We recommend you to host your bot in better hosting like spend some money for vps or free hosting (stozu) and stop hosting your bot in replit or any other services that people can easily find your token. In this issue it is fully your fault you have no rights to report this code.

So the reason why your server got nuked is probably because someone find your token and they use your bot token to nuked your servers.

If you how to coding feel free to look into this repo code and tell me where the part it can nuke discord server or grab your bot token

**Comment by Jetfeliks746** [comment]
Putting your token in the Config file will allow anyone to view your token. I recommend to put your token in a .env file or in your secret keys as those are hidden from the public and only those that have access to project will see it.
