### ISSUE TITLE
Does it uses Spotify API (cause I prefer spotify more than searching the songs in youtube)

### ISSUE THREAD

**Issue by 301Bri** [SudhanPlayz/Discord-MusicBot#1200]
So is it added or do i need some settings??/

**Comment by pwnyprod** [comment]
here is the docu: https://github.com/SudhanPlayz/Discord-MusicBot/wiki/Installation-on-a-Linux-server#get-a-spotify-client-id--secret
here you can find the settings in the config: https://github.com/SudhanPlayz/Discord-MusicBot/blob/master/botconfig.js#L41

and maybe to answer the question i predict you had: no, none of the bots is really able to stream from spotify because spotify use encoded streams in his own application. its nearly the same like netflix and all the others. you cant just fetch the stream. it searches the song title on youtube and use the youtube stream.

**Comment by C-EO** [comment]
are u using v5 or v4

**Comment by 301Bri** [comment]
v5

**Comment by C-EO** [comment]
@301Bri v5 doesn't need you to configure Spotify. It's configured in the lavalink server.
The problem you have is with the lavalink server/node you're connected to

**Comment by LewdHuTao** [comment]
> @301Bri v5 doesn't need you to configure Spotify. It's configured in the lavalink server.
> The problem you have is with the lavalink server/node you're connected to

wdym its already configured in the lavalink server? its always never configured in lavalink plugins, we just move to another spotify wrapper which doesn’t require spotify client id
