### ISSUE TITLE
The music immediately ended after the music began

### ISSUE THREAD

**Issue by LINKlang** [SudhanPlayz/Discord-MusicBot#1251]
**Please describe the problem you are having in as much detail as possible:**

The music immediately ended after the music began
![image](https://github.com/SudhanPlayz/Discord-MusicBot/assets/116951234/e5dabee5-e11d-4e40-835e-0d28d11b9781)
![image](https://github.com/SudhanPlayz/Discord-MusicBot/assets/116951234/37545410-b999-48c0-bad7-6ee9b5380752)

### Essentials:

- Bot Version: master
- Commit Hash: 
- Node.js version: v18.12.1
- Operating system: Replit

### Relevant client options:

- partials: none
- gateway intents: none
- other: none

**Comment by iseeface** [comment]
i recommend you to using v5 version

**Comment by LINKlang** [comment]
> i recommend you to using v5 version

Actually I can't find where Replit switched to v5

**Comment by LINKlang** [comment]
By the way, I also saw this error on Replit
![image](https://github.com/SudhanPlayz/Discord-MusicBot/assets/116951234/34f8652b-9243-4a39-826f-f52ebdfae3a6)

**Comment by LINKlang** [comment]
Try to use Replit to build your own Lavalink server, but there is still a problem
![image](https://github.com/SudhanPlayz/Discord-MusicBot/assets/116951234/0da0431f-0b26-4b24-8a21-0da432cf4bfe)

**Comment by DarrenOfficial** [comment]
> By the way, I also saw this error on Replit ![image](https://user-images.githubusercontent.com/116951234/257968963-34f8652b-9243-4a39-826f-f52ebdfae3a6.png)


This is because of incompatible lavalink version for that specific client you are using. In this case, it's erelajs fault. That project is dead, that's why we are moving away from it in v5. It's in this version FYI https://github.com/wtfnotavailable/Discord-MusicBot/tree/feature/DJSv14

**Comment by theLucasAntunes** [comment]
Exact same error as OP when hosting my own Lavalink server through Replit, running on v5.

> > By the way, I also saw this error on Replit ![image](https://user-images.githubusercontent.com/116951234/257968963-34f8652b-9243-4a39-826f-f52ebdfae3a6.png)
> 
> This is because of incompatible lavalink version for that specific client you are using. In this case, it's erelajs fault. That project is dead, that's why we are moving away from it in v5. It's in this version FYI https://github.com/wtfnotavailable/Discord-MusicBot/tree/feature/DJSv14

So should we ignore the CDN? (https://cdn.darrennathanael.com/jars/cogs/Lavalink.jar)

Because the older Lavalink versions had the 403 YouTube error, and the newest ones don't work, so the CDN isn't helping there. Several SSL servers from the [official list](https://lavalink-list.darrennathanael.com/SSL/lavalink-with-ssl/) are also broken, and I suspect they also depend on the [latest 3.7.8 Lavalink](https://github.com/lavalink-devs/Lavalink/releases/tag/3.7.8), which simply doesn't work with MusicBot.

I found only two SSL public servers working but they sometimes are down, so I wanted to host my own, but I didn't find any documentation/issue mentioning a working `Lavalink.jar`. Probably a modified one is needed?
