### ISSUE TITLE
lavalink issue 

### ISSUE THREAD

**Issue by Naiml007** [SudhanPlayz/Discord-MusicBot#1285]
| Slash Command Loaded: volume
[11:1:2024 - 11:37] | Successfully Logged in as Botx00#4131
[11:1:2024 - 11:37] | Node: Main Node | Lavalink node is connected.
[11:1:2024 - 11:37] | Node: Main Node | Lavalink node has an error: Unexpected op "ready" with data: [object Object].
fatal: not a git repository (or any parent up to mount point /home)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
[11:1:2024 - 11:39] | Player: 994629419790504007 | A wild player has been created in server bot
fatal: not a git repository (or any parent up to mount point /home)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).

------------------------------------
lavalink
	nodes: [
		{
			identifier: "Main Node", //- Used for indentifier in stats commands.
			host: "localnet-id.ajiehost.rf.gd", //- The host name or IP of the lavalink server.
			port: 540, // The port that lavalink is listening to. This must be a number!
			password: "https://dsc.gg/ajidevserver", //- The password of the lavalink server.
			retryAmount: 200, //- The amount of times to retry connecting to the node if connection got dropped.
			retryDelay: 40, //- Delay between reconnect attempts if connection is lost.
			secure: false, //- Can be either true or false. Only use true if ssl is enabled!
		},

**Comment by iakzs** [comment]
i got the same error lol

**Comment by berithpy** [comment]
Same here

**Comment by Naiml007** [comment]
![image](https://github.com/SudhanPlayz/Discord-MusicBot/assets/90306726/ed45f59d-7de9-4fc1-8fbf-e500b7c76a8f)

**Comment by Herjunet** [comment]
anyone know how to solve it?

**Comment by okisooo** [comment]
if you're ever getting the error "Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set)." its probably because git is trying to look for a .git repository but the search across filesystems isnt set to true, also proven by the other log fatal: "not a git repository (or any parent up to mount point /home)", which straight up means it can't find a .git repository

and for the disconnecting error, it looks very similar to the documentation on the lavalink server

![image](https://github.com/SudhanPlayz/Discord-MusicBot/assets/31625368/ca9447ed-86b7-44c4-aa30-22588fd077a5)
https://blog.darrennathanael.com/post/how-to-lavalink/
it's either the bot or the lavalink server that doesn't support the library, so you should try different versions

**Comment by Naiml007** [comment]
lavalink v3.7.10 
lavalink node has an error: Unexpected op "ready" with data: [object Object].

**Comment by ekrekeler** [comment]
I was having problems with musicbot and lavalink in a docker compose environment. Might have been the same issue here, but hard to tell.

I was able to get it working by using the image fredboat/lavalink:v3-update-lp. This is a snapshot built from the [v3-update-lp](https://github.com/lavalink-devs/Lavalink/tree/v3-update-lp) branch. The only difference between this and the 3.7.11 version released in March seems to be a single [commit](https://github.com/lavalink-devs/Lavalink/commit/b0db58a0fd7dcfce4055f0d1f954d19a6f858f12) bumping the lavaplayer version. I have no idea why that makes a difference, but it worked for me.

@Naiml007 I also see this error when starting musicbot, but it appears to be cosmetic because the bot still works fine.
> lavalink node has an error: Unexpected op "ready" with data: [object Object].

**Comment by LewdHuTao** [comment]
> lavalink v3.7.10 lavalink node has an error: Unexpected op "ready" with data: [object Object].

this error has nothing to do with us, the wrapper we use are no longer maintained thats why you get that warning message but the bot still gonna works fine if you configure them correctly
