### ISSUE TITLE
lavalink issue

### ISSUE THREAD

**Issue by sovanmondal182** [SudhanPlayz/Discord-MusicBot#211]
lavalink server not working...help me....i used all other lavalink server...

**Comment by joeyk710** [comment]
First of all, it is rude to say `give a solution` because that is forcing people to help you and that will not get you anywhere. Second of all, have you looked up any solutions on other Lavalink servers to use? Have you tried to self-host it? We do not offer support for Lavalink. We only offer support for this code. Use https://lavalink.org for alternate servers to use.
