### ISSUE TITLE
How move command works

### ISSUE THREAD

**Issue by Nooby69** [SudhanPlayz/Discord-MusicBot#541]
I don't understand how to perform its command if someone can help me by attaching a gif of how it function will help alot!

**Comment by KMPR** [comment]
/m [position of the song you want] [position where you want the song to be]

For example (substitute `/` for the prefix you configured)

`/m 69 10`

moves the song at position 69 in your queue to position 10.

What doesn't work unfortunately is moving a song to position 1 so that it plays next. (Comes up with invalid track position)

**Comment by DarrenOfficial** [comment]
Good explanation.
