### ISSUE TITLE
Issue with move and /queue [v4]

### ISSUE THREAD

**Issue by Vretu-Dev** [SudhanPlayz/Discord-MusicBot#832]
**In version 4 there is a similar problem that occurred in version 5 with moving music to the first place in the queue. This does not work with both the prefix and the slash command.**
![image](https://user-images.githubusercontent.com/82831707/166563771-e2688318-5869-4970-b513-8b8e862e90f4.png)

**Another problem is /queue. After entering this command /queue command is not executed.**
![image](https://user-images.githubusercontent.com/82831707/166564043-dd1d83b3-59d4-449a-84f8-444f2df04df5.png)

**Comment by XstreamSpeed** [comment]
Yeah for some reason destination 1 doesn't work, unsure why though.

**Comment by LewdHuTao** [comment]
this issue is fixed in v5. if you want a solution you can see v5 queue command code

**Comment by LewdHuTao** [comment]
about the queue command it’s probably because there’s too many songs and it can’t fetch all the songs in time, iirc slash only have 3 seconds to responds or else it will show same like the image you send, the solution to this is to use deferReply. so in this case it still use djs 12 which is slash is still bad that time and there is no deferReply
