### ISSUE TITLE
error V5

### ISSUE THREAD

**Issue by LucasB25** [SudhanPlayz/Discord-MusicBot#957]
TypeError: player.setResumeMessage is not a function
at Object.run (/test/events/voiceStateUpdate.js:96:26)

TypeError: player.setPausedMessage is not a function
at Object.run (/test/events/voiceStateUpdate.js:126:26)

**Comment by JotaroKujo0525** [comment]
Elaborate further

**Comment by LucasB25** [comment]
well at each reco deco in the vocal where is the bot these errors its returned

**Comment by Saud-97** [comment]
@BioCla I think that is related to the flip flop implementation.

**Comment by BioCla** [comment]
> @BioCla I think that is related to the flip flop implementation.

Yes, your intuition is correct, that error will only be generated through the flip flop implementation. However, on the latest commit everything works fine, so more inquiry is needed:

@LucasB25 
Have you changed the code in any way shape or form?
Have you made sure that the code is up to date on the latest commit?
Have you made sure that you haven't accidently overlapped some of your changes with the official repo's?

I notice that the lines from which your errors are generated are not the same as the ones on the official repo, which would otherwise be 91 and 121 respectively.

I suspect that you have either changed some imports or changed the names of the variables, alternatively you might have accidently deleted the `EpicPlayer.js` file from `lib\EpicPlayer.js` (though I don't think you went as far, since you haven't  had another crucial error show up)

**Comment by LucasB25** [comment]
> I notice that the lines from which your errors are generated are not the same as the ones on the official repo, which would otherwise be 91 and 121 respectively.

it’s exactly the same. and yes I checked the updates, about the lines that are incorrect it’s simply because I have an extension that makes the code clean

**Comment by BioCla** [comment]
> > I notice that the lines from which your errors are generated are not the same as the ones on the official repo, which would otherwise be 91 and 121 respectively.
> 
> it’s exactly the same. and yes I checked the updates, about the lines that are incorrect it’s simply because I have an extension that makes the code clean

Alright.
could you answer the questions I posed?

**Comment by LucasB25** [comment]
> Have you changed the code in any way shape or form? **NO**
> Have you made sure that the code is up to date on the latest commit? **YES**
> Have you made sure that you haven't accidently overlapped some of your changes with the official repo's? **YES**

**Comment by LucasB25** [comment]
> @LucasB25 `events/voiceStateUpdate.js` had an update in the latest commit [188902c](https://github.com/SudhanPlayz/Discord-MusicBot/commit/188902cc43cfb4f5a7f87582f917a2dd8b31810e). Can you please check and confirm if you're still facing the issue?

It is always there it is really when auto-pause is enabled that this error happens

**Comment by DarrenOfficial** [comment]
I'll close this for now, as there has been 6 days since the last update was given.
